### ISSUE TITLE
Down::ChunkedIO.new fails if enumerator emits frozen strings

### ISSUE THREAD

**Issue by lastobelus** [janko/down#32]
for example:

```
# frozen_string_literal: true
io = Down::ChunkedIO.new(chunks: %w(one two three).each)
IO.copy_stream(io, some_stream)
```

```
=>
    FrozenError:
       can't modify frozen String
     # /Users/lasto/.rvm/gems/ruby-2.5.3/gems/down-4.8.1/lib/down/chunked_io.rb:275:in `force_encoding'
     # /Users/lasto/.rvm/gems/ruby-2.5.3/gems/down-4.8.1/lib/down/chunked_io.rb:275:in `retrieve_chunk'
     # /Users/lasto/.rvm/gems/ruby-2.5.3/gems/down-4.8.1/lib/down/chunked_io.rb:162:in `readpartial'
```

**Comment by janko** [comment]
Thanks for the report. I'm working on fixing this now.

**Comment by janko** [comment]
The fix above won't work in all cases, I need to do some more fixing.
